  ### CUSTOMIZATION LISTEN AND RESOLVE
  - name: ==== Run Customization for Listen and Resolve ====
    run: python3 listenandresolve.py
    shell: bash
    continue-on-error: false
  ### CUSTOMIZATION LISTEN AND RESOLVE
